[package]
name = "atmospheric"
version = "1.2.0"
edition = "2024"
build = "build.rs"


[build-dependencies]
gl_generator = "0.14"


[dependencies]
numeracy = {path = "../numeracy"}
#numeracy = {git = "https://github.com/TheBookwyrms/numeracy.git", branch = "working_branch"}
glfw = { version = "0.60", default-features = false, features = ["prebuilt-libs", "raw-window-handle-v0-6"]}

zune-jpeg = "=0.4.21"
zune-png = "0.4.10"